### ISSUE TITLE
Ustalenie kanału komunikacji

### ISSUE THREAD

**Issue by PatNowak** [PatNowak/praktyki#4]

**Comment by Snopy692** [comment]
Myślę, żeby skupić się na GitHubie, żeby nauczyć się z niego korzystać.
Może od czasu do czasu jakiś Zoom ? No i ewentualnie Whatsapp do ustalania "meetingów" :)

**Comment by PatNowak** [comment]
GitHub i Whatsapp. Także co jakiś czas spotkanie na Zoomie.
