### ISSUE TITLE
Docker problem

### ISSUE THREAD

**Issue by Snopy692** [PatNowak/praktyki#5]
Zainstalowaliśmy z Kacprem  Dockera i po odpaleniu dockera wyświetliło się takie coś:
![image](https://user-images.githubusercontent.com/65659877/83559217-7b9c6f00-a514-11ea-9889-be6f16de3f06.png)
Przeinstalowanie nie pomogło / restart kompa też nie.

**Comment by PatNowak** [comment]
Spróbujcie:
- zainstalować najnowszą wersję VirtualBox
- uruchamiać `Docker QuickStart Terminal` jako admin

źródło: https://github.com/docker/machine/issues/4066

**Comment by PatNowak** [comment]
@Snopy692 Jeżeli Tobie działa, to możesz pomóc Kacprowi.
Mi działa bez problemów na moim kompie (bez odpalania jako admin):
- Windows 10 Home
- VirtualBox 5.2.20 r 125813
- Docker:
```
docker version
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.12
 Git commit:        774a1f4eee
 Built:             Mon Mar  4 10:36:44 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056dbc
  Built:            Thu Apr 11 04:50:00 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by Snopy692** [comment]
Dzięki :)
Dobra to jeżeli mamy ten problem to jak pisał wcześniej Patryk należy zaktualizować `Virtual Boxa`
Możemy go pobrać tutaj [WIN10](https://download.virtualbox.org/virtualbox/6.1.8/VirtualBox-6.1.8-137981-Win.exe) i zainstalować.
Poniżej efekt:
![image](https://user-images.githubusercontent.com/65659877/83777228-76acfc00-a689-11ea-842e-71664b9c2ff8.png)
Nie uruchamiałem `Dockera` jako administrator.

**Comment by PatNowak** [comment]
Zakładam, że temat rozwiązany ;)
