### ISSUE TITLE
Powershell w folderze `praktyki`

### ISSUE THREAD

**Issue by Snopy692** [PatNowak/praktyki#7]
Cześć,

Po kolei opiszę czynności, które wykonałem
1. uruchomiłem `Git Bash` i wpisałem komendę `git clone https://github.com/PatNowak/praktyki.git`
![image](https://user-images.githubusercontent.com/65659877/83787351-f5a73200-a693-11ea-920d-f0601659def7.png) - jest OK
2. w folderze `praktyki` uruchomiłem `Powershella`  (Shift + PPM) - so far so good. 
3. i uruchamiam skrypt:  `./local.ps1 up` i tu pojawia się problem.
`ERROR: .UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb3 in position 23: invalid start byte`
`Error: No such container: mywww` 

![image](https://user-images.githubusercontent.com/65659877/83787756-8d0c8500-a694-11ea-83c5-b07efdbdce5c.png)

Szukałem coś na temat tego błędu i znalazłem [to](https://stackoverflow.com/questions/12468179/unicodedecodeerror-utf8-codec-cant-decode-byte-0x9c) - jakiś problem z dekodowaniem?

**Comment by PatNowak** [comment]
Zatem: zobacz mój najnowszy PR i daj approve.
