### ISSUE TITLE
Dodanie HttpClienta i stworzenie prototypu pierwszego parsera jakiejś strony

### ISSUE THREAD

**Issue by PatNowak** [PatNowak/praktyki#8]
Aby pobierać zawartość stron internetowych, musimy robić żądania HTTP. Aby to zautomatyzować w praktycznie każdym języku programowania możemy zrobić zapytania HTTP.

W PHP możemy je robić na różne sposoby, ale skorzystamy tutaj z Symfony HttpClienta.

Ogólny Plan jest taki: 
- jeśli dodamy sobie z czasem WP, gazeta.pl czy cokolwiek to dla każdej z nich dodamy dwie klasy (przykład dla gazeta.pl)
- GazetaApiClient.php
- GazetaParser.php

ApiClient będzie dziedziczył po abstrakcyjnej klasie ApiClient aby mieć dostęp do HTTPClienta i zapewnimy w ten sposób też jakiś wspólny "interfejs"

Parser zaś będzie implementował (z czasem) interfejs Parser i w nim będziemy mieli całą logikę jak parsujemy te strony tj. jak z nich pobieramy kluczowe dla nas informacje. 

**Oddzielamy to JAK pobieramy dane od tego JAK je przetwarzamy**. 
Dzięki temu kod będzie testowalny.

W tym zadaniu zakres obowiązków:
- dowiedz się jak dodać do repozytorium `HttpClient`  i zrób to (zmiana powinna obejmować composer.json i composer.lock)
- napisz klasę, która zawiera httpClient jako pole obiektu o akcesorze "protected" (nazwij tę klasę `abstract class ApiClient`)
- Stwórz prototyp pierwszego serwisu typu ApiClient np. WpApiClient czy JwOrgApiClient - jakikolwiek
- Zastanów się czy możesz w jakiś sposób przetestować czy Twój kod działa i jeśli tak to zrób to

**Comment by Snopy692** [comment]
Nie wiem czy w odpowiednim miejscu piszę.
Ale tak.. @PatNowak napisał: `dowiedz się jak dodać do repozytorium HttpClient i zrób to (zmiana powinna obejmować composer.json i composer.lock)`

Wydaje mi się, że do sekcji `"require": {...}` w `composer.json i composer.lock` trzeba dodać linijkę `symfony/http-client`

**Comment by PatNowak** [comment]
Odpiszę tu wieczorem :)

**Comment by PatNowak** [comment]
Zasadniczo nie dotykamy samemu wcale tych plików composera ;)
Jak będę miał czas to dodam nieco ułatwień do naszych plików `local.ps1` i `local.sh`, ale chcemy to zrobić tak:

1. Wejdź na kontener www 
`local.ps1 bash www`

2. Zawołaj `composer require` (https://getcomposer.org/doc/03-cli.md#require)
W naszym wypadku chcemy httpClient od symfony czyli https://packagist.org/packages/symfony/http-client
I tam już na tej stronie jest info jak :)

`composer require symfony/http-client`

3. Potem jak już mamy HttpClient, korzystamy z niego poprzez:
- dodanie adnotacji `use` w klasie abstrakcyjnej (zobacz tu przykład: https://symfony.com/doc/current/components/http_client.html#basic-usage)
- stworzenie pola klasy i zainicjalizowanie go w konstruktorze

```
protected $httpClient;

...
public __construct(HttpClientInterface $httpClient) {
    $this->httpClient = $httpClient;
}
```

4. Dziedziczenie po tej klasie absrtrakcyjnej
```
class MyParserClient extends ApiClient
```

W razie pytań, śmiało. Najważniejsze, byście sami coś kombinowali (a zwłaszcza nasz praktykant ;) ).
